In [1]:
import pandas as pd
import numpy as np

In [2]:
print("Welcome to Pandas-5 continuation")

Welcome to Pandas-5 continuation


In [3]:
df = pd.read_csv('Pfizer_1.csv')
df

Date                Drug_Name    Parameter  1:30:00  2:30:00  \
0   15-10-2020  diltiazem hydrochloride  Temperature     23.0     22.0   
1   15-10-2020  diltiazem hydrochloride     Pressure     12.0     13.0   
2   15-10-2020      docetaxel injection  Temperature      NaN     17.0   
3   15-10-2020      docetaxel injection     Pressure      NaN     22.0   
4   15-10-2020   ketamine hydrochloride  Temperature     24.0      NaN   
5   15-10-2020   ketamine hydrochloride     Pressure      8.0      NaN   
6   16-10-2020  diltiazem hydrochloride  Temperature     34.0     35.0   
7   16-10-2020  diltiazem hydrochloride     Pressure     18.0     19.0   
8   16-10-2020      docetaxel injection  Temperature     46.0     47.0   
9   16-10-2020      docetaxel injection     Pressure     23.0     24.0   
10  16-10-2020   ketamine hydrochloride  Temperature      8.0      9.0   
11  16-10-2020   ketamine hydrochloride     Pressure     12.0     12.0   
12  17-10-2020  diltiazem hydrochloride  Temperature     20.0     19.0   
13  17-10-2020  diltiazem hydrochloride     Pressure      3.0      4.0   
14  17-10-2020      docetaxel injection  Temperature     12.0     13.0   
15  17-10-2020      docetaxel injection     Pressure     20.0     22.0   
16  17-10-2020   ketamine hydrochloride  Temperature     13.0     14.0   
17  17-10-2020   ketamine hydrochloride     Pressure      8.0      9.0   

    3:30:00  4:30:00  5:30:00  6:30:00  7:30:00  8:30:00  9:30:00  10:30:00  \
0       NaN     21.0     21.0       22     23.0     21.0     22.0        20   
1       NaN     11.0     13.0       14     16.0     16.0     24.0        18   
2      18.0      NaN     17.0       18      NaN      NaN     23.0        23   
3      22.0      NaN     22.0       23      NaN      NaN     27.0        26   
4       NaN     27.0      NaN       26     25.0     24.0     23.0        22   
5       NaN      7.0      NaN        9     10.0     11.0     10.0         9   
6      36.0     36.0     37.0       38     37.0     38.0     39.0        40   
7      20.0     21.0     22.0       23     24.0     25.0     25.0        24   
8       NaN     48.0     48.0       49     50.0     52.0     55.0        56   
9       NaN     25.0     26.0       27     28.0     29.0     28.0        28   
10     10.0      NaN     11.0       12     12.0     11.0      NaN        13   
11     13.0      NaN     15.0       15     15.0     15.0      NaN        16   
12     19.0     18.0     17.0       16     15.0      NaN     13.0        14   
13      4.0      4.0      6.0        8      9.0      NaN      9.0        11   
14     14.0     15.0     16.0       17     18.0     19.0     20.0        21   
15     22.0     22.0     22.0       23     25.0     26.0     27.0        28   
16     15.0     16.0     17.0       18     19.0     20.0     21.0        22   
17     10.0     11.0     11.0       12     12.0     11.0     12.0        13   

    11:30:00  12:30:00  
0       20.0        21  
1       19.0        20  
2       25.0        25  
3       29.0        28  
4       21.0        20  
5        9.0        11  
6        NaN        42  
7        NaN        27  
8       57.0        58  
9       29.0        30  
10      14.0        15  
11      17.0        18  
12      11.0        10  
13      13.0        14  
14      22.0        23  
15      29.0        28  
16      23.0        24  
17      14.0        15

In [4]:
df_melt = pd.melt(df,
                  id_vars = ['Date', 'Drug_Name', 'Parameter'],
                  var_name = 'Time',
                  value_name = 'Result'
                 )

In [5]:
df_melt

Date                Drug_Name    Parameter      Time  Result
0    15-10-2020  diltiazem hydrochloride  Temperature   1:30:00    23.0
1    15-10-2020  diltiazem hydrochloride     Pressure   1:30:00    12.0
2    15-10-2020      docetaxel injection  Temperature   1:30:00     NaN
3    15-10-2020      docetaxel injection     Pressure   1:30:00     NaN
4    15-10-2020   ketamine hydrochloride  Temperature   1:30:00    24.0
..          ...                      ...          ...       ...     ...
211  17-10-2020  diltiazem hydrochloride     Pressure  12:30:00    14.0
212  17-10-2020      docetaxel injection  Temperature  12:30:00    23.0
213  17-10-2020      docetaxel injection     Pressure  12:30:00    28.0
214  17-10-2020   ketamine hydrochloride  Temperature  12:30:00    24.0
215  17-10-2020   ketamine hydrochloride     Pressure  12:30:00    15.0

[216 rows x 5 columns]

In [6]:
df_melt.shape

(216, 5)

In [7]:
df_tidy = df_melt.pivot(
                index=['Date', 'Drug_Name', 'Time'],
                columns='Parameter',
                values='Result'
            ).reset_index()

In [8]:
df_tidy.head(20)

Parameter        Date                Drug_Name      Time  Pressure  \
0          15-10-2020  diltiazem hydrochloride  10:30:00      18.0   
1          15-10-2020  diltiazem hydrochloride  11:30:00      19.0   
2          15-10-2020  diltiazem hydrochloride  12:30:00      20.0   
3          15-10-2020  diltiazem hydrochloride   1:30:00      12.0   
4          15-10-2020  diltiazem hydrochloride   2:30:00      13.0   
5          15-10-2020  diltiazem hydrochloride   3:30:00       NaN   
6          15-10-2020  diltiazem hydrochloride   4:30:00      11.0   
7          15-10-2020  diltiazem hydrochloride   5:30:00      13.0   
8          15-10-2020  diltiazem hydrochloride   6:30:00      14.0   
9          15-10-2020  diltiazem hydrochloride   7:30:00      16.0   
10         15-10-2020  diltiazem hydrochloride   8:30:00      16.0   
11         15-10-2020  diltiazem hydrochloride   9:30:00      24.0   
12         15-10-2020      docetaxel injection  10:30:00      26.0   
13         15-10-2020      docetaxel injection  11:30:00      29.0   
14         15-10-2020      docetaxel injection  12:30:00      28.0   
15         15-10-2020      docetaxel injection   1:30:00       NaN   
16         15-10-2020      docetaxel injection   2:30:00      22.0   
17         15-10-2020      docetaxel injection   3:30:00      22.0   
18         15-10-2020      docetaxel injection   4:30:00       NaN   
19         15-10-2020      docetaxel injection   5:30:00      22.0   

Parameter  Temperature  
0                 20.0  
1                 20.0  
2                 21.0  
3                 23.0  
4                 22.0  
5                  NaN  
6                 21.0  
7                 21.0  
8                 22.0  
9                 23.0  
10                21.0  
11                22.0  
12                23.0  
13                25.0  
14                25.0  
15                 NaN  
16                17.0  
17                18.0  
18                 NaN  
19                17.0

In [9]:
df_tidy.shape

(108, 5)

In [10]:
df_tidy.isna().sum()

Parameter
Date            0
Drug_Name       0
Time            0
Pressure       13
Temperature    13
dtype: int64

In [11]:
df_tidy[df_tidy['Drug_Name'] == 'diltiazem hydrochloride']

Parameter        Date                Drug_Name      Time  Pressure  \
0          15-10-2020  diltiazem hydrochloride  10:30:00      18.0   
1          15-10-2020  diltiazem hydrochloride  11:30:00      19.0   
2          15-10-2020  diltiazem hydrochloride  12:30:00      20.0   
3          15-10-2020  diltiazem hydrochloride   1:30:00      12.0   
4          15-10-2020  diltiazem hydrochloride   2:30:00      13.0   
5          15-10-2020  diltiazem hydrochloride   3:30:00       NaN   
6          15-10-2020  diltiazem hydrochloride   4:30:00      11.0   
7          15-10-2020  diltiazem hydrochloride   5:30:00      13.0   
8          15-10-2020  diltiazem hydrochloride   6:30:00      14.0   
9          15-10-2020  diltiazem hydrochloride   7:30:00      16.0   
10         15-10-2020  diltiazem hydrochloride   8:30:00      16.0   
11         15-10-2020  diltiazem hydrochloride   9:30:00      24.0   
36         16-10-2020  diltiazem hydrochloride  10:30:00      24.0   
37         16-10-2020  diltiazem hydrochloride  11:30:00       NaN   
38         16-10-2020  diltiazem hydrochloride  12:30:00      27.0   
39         16-10-2020  diltiazem hydrochloride   1:30:00      18.0   
40         16-10-2020  diltiazem hydrochloride   2:30:00      19.0   
41         16-10-2020  diltiazem hydrochloride   3:30:00      20.0   
42         16-10-2020  diltiazem hydrochloride   4:30:00      21.0   
43         16-10-2020  diltiazem hydrochloride   5:30:00      22.0   
44         16-10-2020  diltiazem hydrochloride   6:30:00      23.0   
45         16-10-2020  diltiazem hydrochloride   7:30:00      24.0   
46         16-10-2020  diltiazem hydrochloride   8:30:00      25.0   
47         16-10-2020  diltiazem hydrochloride   9:30:00      25.0   
72         17-10-2020  diltiazem hydrochloride  10:30:00      11.0   
73         17-10-2020  diltiazem hydrochloride  11:30:00      13.0   
74         17-10-2020  diltiazem hydrochloride  12:30:00      14.0   
75         17-10-2020  diltiazem hydrochloride   1:30:00       3.0   
76         17-10-2020  diltiazem hydrochloride   2:30:00       4.0   
77         17-10-2020  diltiazem hydrochloride   3:30:00       4.0   
78         17-10-2020  diltiazem hydrochloride   4:30:00       4.0   
79         17-10-2020  diltiazem hydrochloride   5:30:00       6.0   
80         17-10-2020  diltiazem hydrochloride   6:30:00       8.0   
81         17-10-2020  diltiazem hydrochloride   7:30:00       9.0   
82         17-10-2020  diltiazem hydrochloride   8:30:00       NaN   
83         17-10-2020  diltiazem hydrochloride   9:30:00       9.0   

Parameter  Temperature  
0                 20.0  
1                 20.0  
2                 21.0  
3                 23.0  
4                 22.0  
5                  NaN  
6                 21.0  
7                 21.0  
8                 22.0  
9                 23.0  
10                21.0  
11                22.0  
36                40.0  
37                 NaN  
38                42.0  
39                34.0  
40                35.0  
41                36.0  
42                36.0  
43                37.0  
44                38.0  
45                37.0  
46                38.0  
47                39.0  
72                14.0  
73                11.0  
74                10.0  
75                20.0  
76                19.0  
77                19.0  
78                18.0  
79                17.0  
80                16.0  
81                15.0  
82                 NaN  
83                13.0

In [12]:
df_tidy.groupby('Drug_Name')['Temperature'].mean()

Drug_Name
diltiazem hydrochloride    24.848485
docetaxel injection        30.387097
ketamine hydrochloride     17.709677
Name: Temperature, dtype: float64

In [13]:
df_tidy.groupby(['Drug_Name', 'Date'])['Temperature'].mean()

Drug_Name                Date      
diltiazem hydrochloride  15-10-2020    21.454545
                         16-10-2020    37.454545
                         17-10-2020    15.636364
docetaxel injection      15-10-2020    20.750000
                         16-10-2020    51.454545
                         17-10-2020    17.500000
ketamine hydrochloride   15-10-2020    23.555556
                         16-10-2020    11.500000
                         17-10-2020    18.500000
Name: Temperature, dtype: float64

In [14]:
df_tidy.groupby('Drug_Name').agg({'Pressure':'mean', 'Temperature':'mean'})

Pressure  Temperature
Drug_Name                                      
diltiazem hydrochloride  15.424242    24.848485
docetaxel injection      25.483871    30.387097
ketamine hydrochloride   11.935484    17.709677

In [15]:
df1 = pd.DataFrame([[np.nan,2,np.nan,0],
                    [3,4,np.nan,1],
                    [np.nan, np.nan, np.nan, np.nan],
                    [np.nan,3,np.nan,4]],
                  columns=['A', 'B', 'C', 'D'])

In [16]:
df1

A    B   C    D
0  NaN  2.0 NaN  0.0
1  3.0  4.0 NaN  1.0
2  NaN  NaN NaN  NaN
3  NaN  3.0 NaN  4.0

In [17]:
df1.fillna(0)

A    B    C    D
0  0.0  2.0  0.0  0.0
1  3.0  4.0  0.0  1.0
2  0.0  0.0  0.0  0.0
3  0.0  3.0  0.0  4.0

In [18]:
df1['B'].mean()

3.0

In [19]:
df1['B'].fillna(df1['B'].mean())

0    2.0
1    4.0
2    3.0
3    3.0
Name: B, dtype: float64

In [20]:
df1['A'].fillna(df1['A'].mean())

0    3.0
1    3.0
2    3.0
3    3.0
Name: A, dtype: float64

In [21]:
df1['D'].fillna(df1['D'].mean())

0    0.000000
1    1.000000
2    1.666667
3    4.000000
Name: D, dtype: float64

In [22]:
df_tidy['Pressure'] = df_tidy.groupby('Drug_Name')['Pressure'].transform(lambda x: x.fillna(x.mean()))
df_tidy['Temperature'] = df_tidy.groupby('Drug_Name')['Temperature'].transform(lambda x: x.fillna(x.mean()))

In [23]:
df_tidy.isna().sum()

Parameter
Date           0
Drug_Name      0
Time           0
Pressure       0
Temperature    0
dtype: int64

In [24]:
df_ = pd.DataFrame([[4, 9]] * 3, columns=['A', 'B'])

In [25]:
df_.apply(np.sqrt)

A    B
0  2.0  3.0
1  2.0  3.0
2  2.0  3.0

In [26]:
df_.apply(lambda x: 2, axis=1)

0    2
1    2
2    2
dtype: int64

In [27]:
df_.apply(lambda x: 2, axis=0)

A    2
B    2
dtype: int64

In [28]:
df_.apply(lambda x: x*2, axis=1)

A   B
0  8  18
1  8  18
2  8  18

In [29]:
df_.apply(lambda x: [1, 2], axis=0)

A  B
0  1  1
1  2  2

In [30]:
df_1 = df_.apply(lambda x: [1, 2], axis=1)

In [31]:
type(df_1)

pandas.core.series.Series

In [32]:
df_

A  B
0  4  9
1  4  9
2  4  9

In [33]:
df1.apply(lambda x: x.fillna(x.mean()))

A    B   C         D
0  3.0  2.0 NaN  0.000000
1  3.0  4.0 NaN  1.000000
2  3.0  3.0 NaN  1.666667
3  3.0  3.0 NaN  4.000000

In [34]:
df_tidy.groupby('Drug_Name').apply(lambda x: x.fillna(x.mean()))

Parameter                          Date                Drug_Name      Time  \
Drug_Name                                                                    
diltiazem hydrochloride 0    15-10-2020  diltiazem hydrochloride  10:30:00   
                        1    15-10-2020  diltiazem hydrochloride  11:30:00   
                        2    15-10-2020  diltiazem hydrochloride  12:30:00   
                        3    15-10-2020  diltiazem hydrochloride   1:30:00   
                        4    15-10-2020  diltiazem hydrochloride   2:30:00   
...                                 ...                      ...       ...   
ketamine hydrochloride  103  17-10-2020   ketamine hydrochloride   5:30:00   
                        104  17-10-2020   ketamine hydrochloride   6:30:00   
                        105  17-10-2020   ketamine hydrochloride   7:30:00   
                        106  17-10-2020   ketamine hydrochloride   8:30:00   
                        107  17-10-2020   ketamine hydrochloride   9:30:00   

Parameter                    Pressure  Temperature  
Drug_Name                                           
diltiazem hydrochloride 0        18.0         20.0  
                        1        19.0         20.0  
                        2        20.0         21.0  
                        3        12.0         23.0  
                        4        13.0         22.0  
...                               ...          ...  
ketamine hydrochloride  103      11.0         17.0  
                        104      12.0         18.0  
                        105      12.0         19.0  
                        106      11.0         20.0  
                        107      12.0         21.0  

[108 rows x 5 columns]

In [35]:
# df_tidy= df_tidy.groupby('Drug_Name').apply(lambda x: x.fillna(x.mean()))

In [36]:
df_tidy.isna().sum()

Parameter
Date           0
Drug_Name      0
Time           0
Pressure       0
Temperature    0
dtype: int64

In [37]:
df_tidy

Parameter        Date                Drug_Name      Time  Pressure  \
0          15-10-2020  diltiazem hydrochloride  10:30:00      18.0   
1          15-10-2020  diltiazem hydrochloride  11:30:00      19.0   
2          15-10-2020  diltiazem hydrochloride  12:30:00      20.0   
3          15-10-2020  diltiazem hydrochloride   1:30:00      12.0   
4          15-10-2020  diltiazem hydrochloride   2:30:00      13.0   
..                ...                      ...       ...       ...   
103        17-10-2020   ketamine hydrochloride   5:30:00      11.0   
104        17-10-2020   ketamine hydrochloride   6:30:00      12.0   
105        17-10-2020   ketamine hydrochloride   7:30:00      12.0   
106        17-10-2020   ketamine hydrochloride   8:30:00      11.0   
107        17-10-2020   ketamine hydrochloride   9:30:00      12.0   

Parameter  Temperature  
0                 20.0  
1                 20.0  
2                 21.0  
3                 23.0  
4                 22.0  
..                 ...  
103               17.0  
104               18.0  
105               19.0  
106               20.0  
107               21.0  

[108 rows x 5 columns]

In [38]:
df_tidy.pivot_table(index='Drug_Name',
                   columns='Date',
                   aggfunc=np.min)

Parameter                 Pressure                       Temperature  \
Date                    15-10-2020 16-10-2020 17-10-2020  15-10-2020   
Drug_Name                                                              
diltiazem hydrochloride       11.0  15.424242        3.0   20.000000   
docetaxel injection           22.0  23.000000       20.0   17.000000   
ketamine hydrochloride         7.0  11.935484        8.0   17.709677   

Parameter                                           Time                        
Date                    16-10-2020 17-10-2020 15-10-2020 16-10-2020 17-10-2020  
Drug_Name                                                                       
diltiazem hydrochloride  24.848485       10.0   10:30:00   10:30:00   10:30:00  
docetaxel injection      30.387097       12.0   10:30:00   10:30:00   10:30:00  
ketamine hydrochloride    8.000000       13.0   10:30:00   10:30:00   10:30:00

In [39]:
df_tidy.pivot_table(index='Date',
                   columns='Drug_Name',
                   aggfunc=np.min)

Parameter                 Pressure                                             \
Drug_Name  diltiazem hydrochloride docetaxel injection ketamine hydrochloride   
Date                                                                            
15-10-2020               11.000000                22.0               7.000000   
16-10-2020               15.424242                23.0              11.935484   
17-10-2020                3.000000                20.0               8.000000   

Parameter              Temperature                                             \
Drug_Name  diltiazem hydrochloride docetaxel injection ketamine hydrochloride   
Date                                                                            
15-10-2020               20.000000           17.000000              17.709677   
16-10-2020               24.848485           30.387097               8.000000   
17-10-2020               10.000000           12.000000              13.000000   

Parameter                     Time                                             
Drug_Name  diltiazem hydrochloride docetaxel injection ketamine hydrochloride  
Date                                                                           
15-10-2020                10:30:00            10:30:00               10:30:00  
16-10-2020                10:30:00            10:30:00               10:30:00  
17-10-2020                10:30:00            10:30:00               10:30:00

In [40]:
df_tidy.pivot_table(index='Date',
                   columns='Drug_Name',
                   aggfunc=np.min,
                   margins=True)

Parameter                 Pressure                                             \
Drug_Name  diltiazem hydrochloride docetaxel injection ketamine hydrochloride   
Date                                                                            
15-10-2020                    11.0                22.0                    7.0   
16-10-2020               15.424242                23.0              11.935484   
17-10-2020                     3.0                20.0                    8.0   
All                            3.0                20.0                    7.0   

Parameter                         Temperature                      \
Drug_Name         All diltiazem hydrochloride docetaxel injection   
Date                                                                
15-10-2020        7.0                    20.0                17.0   
16-10-2020  11.935484               24.848485           30.387097   
17-10-2020        3.0                    10.0                12.0   
All               3.0                    10.0                12.0   

Parameter                                                  Time  \
Drug_Name  ketamine hydrochloride   All diltiazem hydrochloride   
Date                                                              
15-10-2020              17.709677  17.0                10:30:00   
16-10-2020                    8.0   8.0                10:30:00   
17-10-2020                   13.0  10.0                10:30:00   
All                           8.0   8.0                10:30:00   

Parameter                                                        
Drug_Name  docetaxel injection ketamine hydrochloride       All  
Date                                                             
15-10-2020            10:30:00               10:30:00  10:30:00  
16-10-2020            10:30:00               10:30:00  10:30:00  
17-10-2020            10:30:00               10:30:00  10:30:00  
All                   10:30:00               10:30:00  10:30:00

In [41]:
df_tidy.pivot_table(index='Date',
                   columns='Drug_Name',
                   margins=True)

Parameter                 Pressure                                             \
Drug_Name  diltiazem hydrochloride docetaxel injection ketamine hydrochloride   
Date                                                                            
15-10-2020               15.952020           25.077957               9.983871   
16-10-2020               21.952020           26.873656              14.322581   
17-10-2020                8.368687           24.500000              11.500000   
All                      15.424242           25.483871              11.935484   

Parameter                         Temperature                      \
Drug_Name         All diltiazem hydrochloride docetaxel injection   
Date                                                                
15-10-2020  17.004616               21.737374           23.962366   
16-10-2020  21.049419               36.404040           49.698925   
17-10-2020  14.789562               16.404040           17.500000   
All         17.614532               24.848485           30.387097   

Parameter                                     
Drug_Name  ketamine hydrochloride        All  
Date                                          
15-10-2020              22.094086  22.597942  
16-10-2020              12.534946  32.879304  
17-10-2020              18.500000  17.468013  
All                     17.709677  24.315086

In [42]:
df_tidy

Parameter        Date                Drug_Name      Time  Pressure  \
0          15-10-2020  diltiazem hydrochloride  10:30:00      18.0   
1          15-10-2020  diltiazem hydrochloride  11:30:00      19.0   
2          15-10-2020  diltiazem hydrochloride  12:30:00      20.0   
3          15-10-2020  diltiazem hydrochloride   1:30:00      12.0   
4          15-10-2020  diltiazem hydrochloride   2:30:00      13.0   
..                ...                      ...       ...       ...   
103        17-10-2020   ketamine hydrochloride   5:30:00      11.0   
104        17-10-2020   ketamine hydrochloride   6:30:00      12.0   
105        17-10-2020   ketamine hydrochloride   7:30:00      12.0   
106        17-10-2020   ketamine hydrochloride   8:30:00      11.0   
107        17-10-2020   ketamine hydrochloride   9:30:00      12.0   

Parameter  Temperature  
0                 20.0  
1                 20.0  
2                 21.0  
3                 23.0  
4                 22.0  
..                 ...  
103               17.0  
104               18.0  
105               19.0  
106               20.0  
107               21.0  

[108 rows x 5 columns]

In [43]:
temp_bins=[5,20,35,50,60]
temp_labels=['low', 'medium', 'high', 'very_high']
df_tidy['temp_cat'] = pd.cut(df_tidy['Temperature'],
       bins=temp_bins,
                             right=False,
       labels=temp_labels)

In [44]:
df_tidy

Parameter        Date                Drug_Name      Time  Pressure  \
0          15-10-2020  diltiazem hydrochloride  10:30:00      18.0   
1          15-10-2020  diltiazem hydrochloride  11:30:00      19.0   
2          15-10-2020  diltiazem hydrochloride  12:30:00      20.0   
3          15-10-2020  diltiazem hydrochloride   1:30:00      12.0   
4          15-10-2020  diltiazem hydrochloride   2:30:00      13.0   
..                ...                      ...       ...       ...   
103        17-10-2020   ketamine hydrochloride   5:30:00      11.0   
104        17-10-2020   ketamine hydrochloride   6:30:00      12.0   
105        17-10-2020   ketamine hydrochloride   7:30:00      12.0   
106        17-10-2020   ketamine hydrochloride   8:30:00      11.0   
107        17-10-2020   ketamine hydrochloride   9:30:00      12.0   

Parameter  Temperature temp_cat  
0                 20.0   medium  
1                 20.0   medium  
2                 21.0   medium  
3                 23.0   medium  
4                 22.0   medium  
..                 ...      ...  
103               17.0      low  
104               18.0      low  
105               19.0      low  
106               20.0   medium  
107               21.0   medium  

[108 rows x 6 columns]

In [45]:
df_tidy['temp_cat'].value_counts()

low          44
medium       43
high         15
very_high     6
Name: temp_cat, dtype: int64

In [46]:
df_tidy.loc[df_tidy['Drug_Name'].str.contains('hydrochloride')]

Parameter        Date                Drug_Name      Time  Pressure  \
0          15-10-2020  diltiazem hydrochloride  10:30:00      18.0   
1          15-10-2020  diltiazem hydrochloride  11:30:00      19.0   
2          15-10-2020  diltiazem hydrochloride  12:30:00      20.0   
3          15-10-2020  diltiazem hydrochloride   1:30:00      12.0   
4          15-10-2020  diltiazem hydrochloride   2:30:00      13.0   
..                ...                      ...       ...       ...   
103        17-10-2020   ketamine hydrochloride   5:30:00      11.0   
104        17-10-2020   ketamine hydrochloride   6:30:00      12.0   
105        17-10-2020   ketamine hydrochloride   7:30:00      12.0   
106        17-10-2020   ketamine hydrochloride   8:30:00      11.0   
107        17-10-2020   ketamine hydrochloride   9:30:00      12.0   

Parameter  Temperature temp_cat  
0                 20.0   medium  
1                 20.0   medium  
2                 21.0   medium  
3                 23.0   medium  
4                 22.0   medium  
..                 ...      ...  
103               17.0      low  
104               18.0      low  
105               19.0      low  
106               20.0   medium  
107               21.0   medium  

[72 rows x 6 columns]

In [47]:
df_tidy['Timestamp']=df_tidy['Date']+ ' ' + df_tidy['Time']
df_tidy

Parameter        Date                Drug_Name      Time  Pressure  \
0          15-10-2020  diltiazem hydrochloride  10:30:00      18.0   
1          15-10-2020  diltiazem hydrochloride  11:30:00      19.0   
2          15-10-2020  diltiazem hydrochloride  12:30:00      20.0   
3          15-10-2020  diltiazem hydrochloride   1:30:00      12.0   
4          15-10-2020  diltiazem hydrochloride   2:30:00      13.0   
..                ...                      ...       ...       ...   
103        17-10-2020   ketamine hydrochloride   5:30:00      11.0   
104        17-10-2020   ketamine hydrochloride   6:30:00      12.0   
105        17-10-2020   ketamine hydrochloride   7:30:00      12.0   
106        17-10-2020   ketamine hydrochloride   8:30:00      11.0   
107        17-10-2020   ketamine hydrochloride   9:30:00      12.0   

Parameter  Temperature temp_cat            Timestamp  
0                 20.0   medium  15-10-2020 10:30:00  
1                 20.0   medium  15-10-2020 11:30:00  
2                 21.0   medium  15-10-2020 12:30:00  
3                 23.0   medium   15-10-2020 1:30:00  
4                 22.0   medium   15-10-2020 2:30:00  
..                 ...      ...                  ...  
103               17.0      low   17-10-2020 5:30:00  
104               18.0      low   17-10-2020 6:30:00  
105               19.0      low   17-10-2020 7:30:00  
106               20.0   medium   17-10-2020 8:30:00  
107               21.0   medium   17-10-2020 9:30:00  

[108 rows x 7 columns]

In [48]:
df_tidy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 108 entries, 0 to 107
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   Date         108 non-null    object  
 1   Drug_Name    108 non-null    object  
 2   Time         108 non-null    object  
 3   Pressure     108 non-null    float64 
 4   Temperature  108 non-null    float64 
 5   temp_cat     108 non-null    category
 6   Timestamp    108 non-null    object  
dtypes: category(1), float64(2), object(4)
memory usage: 5.5+ KB


In [49]:
df_tidy['Timestamp']=pd.to_datetime(df_tidy['Timestamp'])
df_tidy

Parameter        Date                Drug_Name      Time  Pressure  \
0          15-10-2020  diltiazem hydrochloride  10:30:00      18.0   
1          15-10-2020  diltiazem hydrochloride  11:30:00      19.0   
2          15-10-2020  diltiazem hydrochloride  12:30:00      20.0   
3          15-10-2020  diltiazem hydrochloride   1:30:00      12.0   
4          15-10-2020  diltiazem hydrochloride   2:30:00      13.0   
..                ...                      ...       ...       ...   
103        17-10-2020   ketamine hydrochloride   5:30:00      11.0   
104        17-10-2020   ketamine hydrochloride   6:30:00      12.0   
105        17-10-2020   ketamine hydrochloride   7:30:00      12.0   
106        17-10-2020   ketamine hydrochloride   8:30:00      11.0   
107        17-10-2020   ketamine hydrochloride   9:30:00      12.0   

Parameter  Temperature temp_cat           Timestamp  
0                 20.0   medium 2020-10-15 10:30:00  
1                 20.0   medium 2020-10-15 11:30:00  
2                 21.0   medium 2020-10-15 12:30:00  
3                 23.0   medium 2020-10-15 01:30:00  
4                 22.0   medium 2020-10-15 02:30:00  
..                 ...      ...                 ...  
103               17.0      low 2020-10-17 05:30:00  
104               18.0      low 2020-10-17 06:30:00  
105               19.0      low 2020-10-17 07:30:00  
106               20.0   medium 2020-10-17 08:30:00  
107               21.0   medium 2020-10-17 09:30:00  

[108 rows x 7 columns]

In [50]:
df_tidy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 108 entries, 0 to 107
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype         
---  ------       --------------  -----         
 0   Date         108 non-null    object        
 1   Drug_Name    108 non-null    object        
 2   Time         108 non-null    object        
 3   Pressure     108 non-null    float64       
 4   Temperature  108 non-null    float64       
 5   temp_cat     108 non-null    category      
 6   Timestamp    108 non-null    datetime64[ns]
dtypes: category(1), datetime64[ns](1), float64(2), object(3)
memory usage: 5.5+ KB


In [51]:
ts=df_tidy['Timestamp'][0]
ts

Timestamp('2020-10-15 10:30:00')

In [52]:
ts.year

2020

In [53]:
ts.month

10

In [54]:
ts.day

15

In [55]:
ts.month_name()

'October'

In [56]:
ts.day_name()

'Thursday'

In [57]:
ts.dayofweek

3

In [58]:
ts.hour

10

In [59]:
ts.minute

30

In [60]:
ts.second

0

In [61]:
df_tidy['Timestamp'].dt

In [62]:
df_tidy['Timestamp'].dt.year

0      2020
1      2020
2      2020
3      2020
4      2020
       ... 
103    2020
104    2020
105    2020
106    2020
107    2020
Name: Timestamp, Length: 108, dtype: int64

In [89]:
df_tidy[df_tidy['Timestamp'] > '2020-10-16']

Parameter        Date                Drug_Name      Time   Pressure  \
36         16-10-2020  diltiazem hydrochloride  10:30:00  24.000000   
37         16-10-2020  diltiazem hydrochloride  11:30:00  15.424242   
38         16-10-2020  diltiazem hydrochloride  12:30:00  27.000000   
39         16-10-2020  diltiazem hydrochloride   1:30:00  18.000000   
40         16-10-2020  diltiazem hydrochloride   2:30:00  19.000000   
..                ...                      ...       ...        ...   
103        17-10-2020   ketamine hydrochloride   5:30:00  11.000000   
104        17-10-2020   ketamine hydrochloride   6:30:00  12.000000   
105        17-10-2020   ketamine hydrochloride   7:30:00  12.000000   
106        17-10-2020   ketamine hydrochloride   8:30:00  11.000000   
107        17-10-2020   ketamine hydrochloride   9:30:00  12.000000   

Parameter  Temperature temp_cat           Timestamp  
36           40.000000     high 2020-10-16 10:30:00  
37           24.848485   medium 2020-10-16 11:30:00  
38           42.000000     high 2020-10-16 12:30:00  
39           34.000000   medium 2020-10-16 01:30:00  
40           35.000000     high 2020-10-16 02:30:00  
..                 ...      ...                 ...  
103          17.000000      low 2020-10-17 05:30:00  
104          18.000000      low 2020-10-17 06:30:00  
105          19.000000      low 2020-10-17 07:30:00  
106          20.000000   medium 2020-10-17 08:30:00  
107          21.000000   medium 2020-10-17 09:30:00  

[72 rows x 7 columns]

In [91]:
df_tidy[df_tidy['Timestamp'] > '14-10-2020']

Parameter        Date                Drug_Name      Time  Pressure  \
0          15-10-2020  diltiazem hydrochloride  10:30:00      18.0   
1          15-10-2020  diltiazem hydrochloride  11:30:00      19.0   
2          15-10-2020  diltiazem hydrochloride  12:30:00      20.0   
3          15-10-2020  diltiazem hydrochloride   1:30:00      12.0   
4          15-10-2020  diltiazem hydrochloride   2:30:00      13.0   
..                ...                      ...       ...       ...   
103        17-10-2020   ketamine hydrochloride   5:30:00      11.0   
104        17-10-2020   ketamine hydrochloride   6:30:00      12.0   
105        17-10-2020   ketamine hydrochloride   7:30:00      12.0   
106        17-10-2020   ketamine hydrochloride   8:30:00      11.0   
107        17-10-2020   ketamine hydrochloride   9:30:00      12.0   

Parameter  Temperature temp_cat           Timestamp  
0                 20.0   medium 2020-10-15 10:30:00  
1                 20.0   medium 2020-10-15 11:30:00  
2                 21.0   medium 2020-10-15 12:30:00  
3                 23.0   medium 2020-10-15 01:30:00  
4                 22.0   medium 2020-10-15 02:30:00  
..                 ...      ...                 ...  
103               17.0      low 2020-10-17 05:30:00  
104               18.0      low 2020-10-17 06:30:00  
105               19.0      low 2020-10-17 07:30:00  
106               20.0   medium 2020-10-17 08:30:00  
107               21.0   medium 2020-10-17 09:30:00  

[108 rows x 7 columns]

In [92]:
df_tidy[df_tidy['Timestamp'] > '14-10-2020 09:00:00']

Parameter        Date                Drug_Name      Time  Pressure  \
0          15-10-2020  diltiazem hydrochloride  10:30:00      18.0   
1          15-10-2020  diltiazem hydrochloride  11:30:00      19.0   
2          15-10-2020  diltiazem hydrochloride  12:30:00      20.0   
3          15-10-2020  diltiazem hydrochloride   1:30:00      12.0   
4          15-10-2020  diltiazem hydrochloride   2:30:00      13.0   
..                ...                      ...       ...       ...   
103        17-10-2020   ketamine hydrochloride   5:30:00      11.0   
104        17-10-2020   ketamine hydrochloride   6:30:00      12.0   
105        17-10-2020   ketamine hydrochloride   7:30:00      12.0   
106        17-10-2020   ketamine hydrochloride   8:30:00      11.0   
107        17-10-2020   ketamine hydrochloride   9:30:00      12.0   

Parameter  Temperature temp_cat           Timestamp  
0                 20.0   medium 2020-10-15 10:30:00  
1                 20.0   medium 2020-10-15 11:30:00  
2                 21.0   medium 2020-10-15 12:30:00  
3                 23.0   medium 2020-10-15 01:30:00  
4                 22.0   medium 2020-10-15 02:30:00  
..                 ...      ...                 ...  
103               17.0      low 2020-10-17 05:30:00  
104               18.0      low 2020-10-17 06:30:00  
105               19.0      low 2020-10-17 07:30:00  
106               20.0   medium 2020-10-17 08:30:00  
107               21.0   medium 2020-10-17 09:30:00  

[108 rows x 7 columns]

In [63]:
np.random.randint(1,10)

3

In [64]:
a1=np.arange(1,16).reshape((3,-1))+np.random.randint(1,10, (3,5))

In [65]:
a1

array([[ 7, 10,  8,  9, 12],
       [ 9, 16, 12, 11, 11],
       [20, 20, 14, 19, 19]])

In [66]:
a1.min(axis=1)

array([ 7,  9, 14])

In [67]:
a1.argmin(axis=1)

array([0, 0, 2], dtype=int64)

In [68]:
np.amin(a1, axis=-1)

array([ 7,  9, 14])

In [69]:
np.take_along_axis(a1, np.expand_dims(a1.argmin(axis=1), axis=-1), axis=-1)

array([[ 7],
       [ 9],
       [14]])

In [70]:
np.min(a1, axis=1)

array([ 7,  9, 14])

In [71]:
np.max(a1, axis=1)

array([12, 16, 20])

In [72]:
np.max(a1, axis=1)/np.min(a1, axis=1)

array([1.71428571, 1.77777778, 1.42857143])

In [73]:
df_tidy.iloc[df_tidy['Pressure'].argmax()]

Parameter
Date                    16-10-2020
Drug_Name      docetaxel injection
Time                      12:30:00
Pressure                      30.0
Temperature                   58.0
temp_cat                 very_high
Timestamp      2020-10-16 12:30:00
Name: 50, dtype: object

In [74]:
arr = np.arange(1,10).reshape(3,3)

In [75]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [76]:
sum(np.diag(arr))

15

In [77]:
# arr.where(np.diagonal=True)

In [78]:
np.diagonal(arr).sum()

15

In [79]:
sum(np.diagonal(arr))

15

In [80]:
arr = np.array([0,1,0,2,0,0,3,0,5,7,0,0,8])

In [81]:
np.where(arr==0)[0]

array([ 0,  2,  4,  5,  7, 10, 11], dtype=int64)

In [82]:
np.argwhere(arr==0)

array([[ 0],
       [ 2],
       [ 4],
       [ 5],
       [ 7],
       [10],
       [11]], dtype=int64)

In [83]:
df_tidy

Parameter        Date                Drug_Name      Time  Pressure  \
0          15-10-2020  diltiazem hydrochloride  10:30:00      18.0   
1          15-10-2020  diltiazem hydrochloride  11:30:00      19.0   
2          15-10-2020  diltiazem hydrochloride  12:30:00      20.0   
3          15-10-2020  diltiazem hydrochloride   1:30:00      12.0   
4          15-10-2020  diltiazem hydrochloride   2:30:00      13.0   
..                ...                      ...       ...       ...   
103        17-10-2020   ketamine hydrochloride   5:30:00      11.0   
104        17-10-2020   ketamine hydrochloride   6:30:00      12.0   
105        17-10-2020   ketamine hydrochloride   7:30:00      12.0   
106        17-10-2020   ketamine hydrochloride   8:30:00      11.0   
107        17-10-2020   ketamine hydrochloride   9:30:00      12.0   

Parameter  Temperature temp_cat           Timestamp  
0                 20.0   medium 2020-10-15 10:30:00  
1                 20.0   medium 2020-10-15 11:30:00  
2                 21.0   medium 2020-10-15 12:30:00  
3                 23.0   medium 2020-10-15 01:30:00  
4                 22.0   medium 2020-10-15 02:30:00  
..                 ...      ...                 ...  
103               17.0      low 2020-10-17 05:30:00  
104               18.0      low 2020-10-17 06:30:00  
105               19.0      low 2020-10-17 07:30:00  
106               20.0   medium 2020-10-17 08:30:00  
107               21.0   medium 2020-10-17 09:30:00  

[108 rows x 7 columns]

In [84]:
df_tidy.Drug_Name.value_counts().reset_index()

index  Drug_Name
0      docetaxel injection         36
1   ketamine hydrochloride         36
2  diltiazem hydrochloride         36

In [85]:
res=df_tidy.Drug_Name.value_counts()

In [86]:
type(res)

pandas.core.series.Series

In [87]:
res.index

Index(['docetaxel injection', 'ketamine hydrochloride',
       'diltiazem hydrochloride'],
      dtype='object')

In [88]:
res.values

array([36, 36, 36], dtype=int64)